services:
  http-dynamix-api-service-tests:
    image: http-dynamix-api-service-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - http-dynamix-tests

    # Common Test Commands:
    # Here we have some command that can be used as an examples.
    # Uncomment the command that you want to use and comment the rest of the commands.
    ##############################################################
    ##### NOTE: Just one command should be uncommented at a time #
    ##############################################################
    #
    #######################################################
    ##### NOTE: Examples are based on httpbin.org service #
    #######################################################

    ###########################################################################
    # Run all tests                                                           #
    ###########################################################################
    # command: ["run", "--checks", "all", "--workers", "auto"]

networks:
 http-dynamix-tests:
