services:
  http-dynamix-api-service-tests:
    image: http-dynamix-api-service-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
    networks:
      - http-dynamix-tests
    command: ["pytest", "-n", "auto", "tests"]

networks:
  http-dynamix-tests: