name: Label PRs
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      with:
        sync-labels: false
        dot: true
